---
"$schema": "http://json-schema.org/schema#"
id: "boxhatter://action.yaml#"
type: object
required:
    - image
    - command
properties:
    image:
        type: string
        description: container image
    command:
        type: string
        description: shell commands
...
