---
"$schema": "http://json-schema.org/schema#"
id: "hatter://project.yaml#"
title: Project
description: Project configuration
type: object
required:
    - domain
    - ssh_username
    - ssh_password
    - script
properties:
    uri:
        title: URI
        description: |
            Libvirt URI
        type: string
        default: "qemu:///system"
    domain:
        title: Domain
        description: |
            Domain registered with libvirt used as execution environment
        type: string
    snapshot:
        title: Snapshot
        description: |
            Snapshot used as initial execution environment state
        type: string
    ssh_username:
        title: SSH key
        description: |
            Username for connecting to VM guest SSH daemon
        type: string
    ssh_password:
        title: SSH password
        description: |
            Password for connecting to VM guest SSH daemon
        type: string
    script:
        title: Script
        description: |
            List of shell commands executed inside VM guest
        type: array
        items:
            title: Command
            description: |
                Single shell command
            type: string
...
