---
"$schema": "http://json-schema.org/schema#"
id: "hatter://project.yaml#"
title: Project
description: Project configuration
type: object
required:
    - vm
    - ssh
    - script
properties:
    vm:
        title: VM
        description: VM configuration
        type: object
        required:
            - domain
        properties:
            uri:
                title: URI
                description: Libvirt URI
                type: string
                default: "qemu:///system"
            domain:
                title: Domain
                description: |
                    Domain registered with libvirt used as execution
                    environment
                type: string
            snapshot:
                title: Snapshot
                description: |
                    Snapshot used as initial execution environment state
                type: string
            temp_snapshot:
                title: Temporary snapshot
                description: |
                    Snapshot used for storing initial domain state
                type: string
                default: temp_hatter
            get_address_retry_count:
                title: Get address retry count
                description: |
                    Maximum number of retries for obtaining running VM guest
                    IP address
                type: integer
                default: 10
            get_address_delay:
                title: Get address delay
                description: |
                    Delay in seconds between successive get address requests
                type: number
                default: 5
    ssh:
        title: SSH
        description: VM guest SSH daemon configuration
        type: object
        required:
            - username
            - password
        properties:
            username:
                title: Username
                description: Username for connecting to VM guest SSH daemon
                type: string
            password:
                title: Password
                description: Password for connecting to VM guest SSH daemon
                type: string
            connect_retry_count:
                title: Connect retry count
                description: |
                    Maximum number of connect retries
                type: integer
                default: 10
            connect_delay:
                title: Connect delay
                description: |
                    Delay in seconds between successive connect calls
                type: number
                default: 5
            connect_timeout:
                title: Connect timeout
                description: |
                    Single connect's TCP connect timeout and authenticate
                    timeout in seconds
                type: number
                default: 1
    script:
        title: Script
        description: |
            List of shell commands executed inside VM guest
        type: array
        items:
            title: Command
            description: |
                Single shell command
            type: string
...
